// Generated by CoffeeScript 1.7.1
(function() {
  var app;

  app = angular.module('app', []);

  app.controller('mainController', function($scope) {
    return $scope.title = 'Обработка изображений';
  });

  app.controller('uploadController', function($scope, fileUpload) {
    $scope.imageUrl = '/images/';
    return $scope.upload = function() {
      var file, uploadUrl;
      file = $scope.image;
      uploadUrl = "upload";
      console.log('file is ' + JSON.stringify(file));
      return fileUpload(file, uploadUrl, function(data) {
        return $scope.imageUrl += data;
      });
    };
  });

  app.directive('fileModel', function($parse) {
    return {
      restrict: 'A',
      link: function(scope, element, attrs) {
        var model, modelSetter;
        model = $parse(attrs.fileModel);
        modelSetter = model.assign;
        return element.bind('change', function() {
          return scope.$apply(function() {
            return modelSetter(scope, element[0].files[0]);
          });
        });
      }
    };
  });

  app.factory('fileUpload', function($http) {
    var uploadFileToUrl;
    return uploadFileToUrl = function(file, uploadUrl, callback) {
      var fd;
      fd = new FormData;
      fd.append('file', file);
      return $http.post(uploadUrl, fd, {
        transformRequest: angular.identity,
        headers: {
          'Content-Type': void 0
        }
      }).success(function(data) {
        return callback(data);
      }).error(function() {});
    };
  });

}).call(this);
