// Generated by CoffeeScript 1.7.1
(function () {
    var app;

    app = angular.module('app', []);

    app.constant('config', {
        imagesPath: 'images',
        applyFilterUrl: 'applyFilter',
        uploadUrl: 'upload'
    });

    app.controller('mainController', function ($scope, $http, config, fileUpload) {
        var getSessionImage;
        getSessionImage = function () {
            return $http.get('getImage').success(function (fileName) {
                if (fileName) {
                    return $scope.image = config.imagesPath + '/' + fileName;
                }
            });
        };
        $scope.applyFilter = function (data) {
            console.log(data);
            return $http({
                url: config.applyFilterUrl,
                method: 'get',
                params: data
            }).success(function (fileName) {
                return $scope.outputImage = config.imagesPath + '/' + fileName;
            }).error(function (data) {
                return alert('Упс! Что-то пошло не так.');
            });
        };
        $scope.uploadImage = function () {
            var file;
            file = $scope.newImage;
            console.log('file is ' + JSON.stringify(file));
            return fileUpload(file, config.uploadUrl, function (fileName) {
                return $scope.image = config.imagesPath + '/' + fileName;
            });
        };
        return getSessionImage();
    });

    app.directive('fileModel', function ($parse) {
        return {
            restrict: 'A',
            link: function (scope, element, attrs) {
                var model, modelSetter;
                model = $parse(attrs.fileModel);
                modelSetter = model.assign;
                return element.bind('change', function () {
                    return scope.$apply(function () {
                        return modelSetter(scope, element[0].files[0]);
                    });
                });
            }
        };
    });

    app.factory('fileUpload', function ($http, $log) {
        var uploadFileToUrl;
        return uploadFileToUrl = function (file, uploadUrl, callback) {
            var fd;
            fd = new FormData;
            fd.append('file', file);
            return $http.post(uploadUrl, fd, {
                transformRequest: angular.identity,
                headers: {
                    'Content-Type': void 0
                }
            }).success(function (data) {
                return callback(data);
            }).error(function () {
                return $log.error('cannot upload file');
            });
        };
    });

}).call(this);
